//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18449
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_CIF.Proxies.Categoria {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CategoriaDTO", Namespace="http://schemas.datacontract.org/2004/07/SistemaCIF_Service.DTOS")]
    [System.SerializableAttribute()]
    public partial class CategoriaDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoriaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoriaId {
            get {
                return this.CategoriaIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoriaIdField, value) != true)) {
                    this.CategoriaIdField = value;
                    this.RaisePropertyChanged("CategoriaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Proxies.Categoria.ICategoriaService")]
    public interface ICategoriaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategoriaService/DoWork", ReplyAction="http://tempuri.org/ICategoriaService/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategoriaService/DoWork", ReplyAction="http://tempuri.org/ICategoriaService/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategoriaService/ObtenerCategoria", ReplyAction="http://tempuri.org/ICategoriaService/ObtenerCategoriaResponse")]
        Sistema_CIF.Proxies.Categoria.CategoriaDTO[] ObtenerCategoria();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategoriaService/ObtenerCategoria", ReplyAction="http://tempuri.org/ICategoriaService/ObtenerCategoriaResponse")]
        System.Threading.Tasks.Task<Sistema_CIF.Proxies.Categoria.CategoriaDTO[]> ObtenerCategoriaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategoriaService/CrearCategoria", ReplyAction="http://tempuri.org/ICategoriaService/CrearCategoriaResponse")]
        void CrearCategoria(Sistema_CIF.Proxies.Categoria.CategoriaDTO CategoriaDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategoriaService/CrearCategoria", ReplyAction="http://tempuri.org/ICategoriaService/CrearCategoriaResponse")]
        System.Threading.Tasks.Task CrearCategoriaAsync(Sistema_CIF.Proxies.Categoria.CategoriaDTO CategoriaDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategoriaService/RemoverCategoria", ReplyAction="http://tempuri.org/ICategoriaService/RemoverCategoriaResponse")]
        void RemoverCategoria(Sistema_CIF.Proxies.Categoria.CategoriaDTO CategoriaDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategoriaService/RemoverCategoria", ReplyAction="http://tempuri.org/ICategoriaService/RemoverCategoriaResponse")]
        System.Threading.Tasks.Task RemoverCategoriaAsync(Sistema_CIF.Proxies.Categoria.CategoriaDTO CategoriaDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategoriaService/EditarCategoria", ReplyAction="http://tempuri.org/ICategoriaService/EditarCategoriaResponse")]
        void EditarCategoria(Sistema_CIF.Proxies.Categoria.CategoriaDTO CategoriaDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategoriaService/EditarCategoria", ReplyAction="http://tempuri.org/ICategoriaService/EditarCategoriaResponse")]
        System.Threading.Tasks.Task EditarCategoriaAsync(Sistema_CIF.Proxies.Categoria.CategoriaDTO CategoriaDTO);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICategoriaServiceChannel : Sistema_CIF.Proxies.Categoria.ICategoriaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CategoriaServiceClient : System.ServiceModel.ClientBase<Sistema_CIF.Proxies.Categoria.ICategoriaService>, Sistema_CIF.Proxies.Categoria.ICategoriaService {
        
        public CategoriaServiceClient() {
        }
        
        public CategoriaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CategoriaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CategoriaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CategoriaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public Sistema_CIF.Proxies.Categoria.CategoriaDTO[] ObtenerCategoria() {
            return base.Channel.ObtenerCategoria();
        }
        
        public System.Threading.Tasks.Task<Sistema_CIF.Proxies.Categoria.CategoriaDTO[]> ObtenerCategoriaAsync() {
            return base.Channel.ObtenerCategoriaAsync();
        }
        
        public void CrearCategoria(Sistema_CIF.Proxies.Categoria.CategoriaDTO CategoriaDTO) {
            base.Channel.CrearCategoria(CategoriaDTO);
        }
        
        public System.Threading.Tasks.Task CrearCategoriaAsync(Sistema_CIF.Proxies.Categoria.CategoriaDTO CategoriaDTO) {
            return base.Channel.CrearCategoriaAsync(CategoriaDTO);
        }
        
        public void RemoverCategoria(Sistema_CIF.Proxies.Categoria.CategoriaDTO CategoriaDTO) {
            base.Channel.RemoverCategoria(CategoriaDTO);
        }
        
        public System.Threading.Tasks.Task RemoverCategoriaAsync(Sistema_CIF.Proxies.Categoria.CategoriaDTO CategoriaDTO) {
            return base.Channel.RemoverCategoriaAsync(CategoriaDTO);
        }
        
        public void EditarCategoria(Sistema_CIF.Proxies.Categoria.CategoriaDTO CategoriaDTO) {
            base.Channel.EditarCategoria(CategoriaDTO);
        }
        
        public System.Threading.Tasks.Task EditarCategoriaAsync(Sistema_CIF.Proxies.Categoria.CategoriaDTO CategoriaDTO) {
            return base.Channel.EditarCategoriaAsync(CategoriaDTO);
        }
    }
}
