//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaCIF_Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedor
    {
        public int Id { get; set; }
        public string ProveedorId { get; set; }
        public string NombreEmpresa { get; set; }
        public string TelefonoEmpresa { get; set; }
        public string Direccion { get; set; }
        public string TiendaId { get; set; }
        public string Email { get; set; }
        public string TipoProveedor { get; set; }
        public string NombreEncargado { get; set; }
        public string TelefonoEncargado { get; set; }
        public string ApellidoEncargado { get; set; }
        public string Identidadencargado { get; set; }
        public string TipoProducto { get; set; }
    }
}
