//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaCIF_Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int Id { get; set; }
        public string UsuarioId { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Contrasena { get; set; }
        public string ConfirmacionContrasena { get; set; }
        public string Telefono { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string PrivilegioId { get; set; }
        public string Sexo { get; set; }
        public string Cargo { get; set; }
        public string Direccion { get; set; }
        public string Email { get; set; }
        public string Identidad { get; set; }
        public string RolId { get; set; }
    
        public virtual Privilegio Privilegio { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
