//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaCIF_Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VentasCredito
    {
        public int id { get; set; }
        public string VentaId { get; set; }
        public string LocalId { get; set; }
        public string FacturaId { get; set; }
        public string ClienteId { get; set; }
        public string NombreCliente { get; set; }
        public string ProductoId { get; set; }
        public string TiendaId { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> Impuesto { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<decimal> Extras { get; set; }
        public Nullable<System.DateTime> FechaCredito { get; set; }
    }
}
